spring:
  application:
    name: tradeConnect-api

  datasource:
    url: jdbc:mysql://localhost:3306/tradeconnect
    username: root
    password: Paranie29$$
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: codbot29@gmail.com
    password: Paranie29$$
    properties:
        mail:
            smtp:
            auth: true
            starttls:
                enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
    secret: Tm+Qi1z8QTH2MjkGVnN/HV8cdYgvnNvVhHf5XaHlKmQ=
